"""create categories and products

Revision ID: 2886c2bed4d4
Revises: 
Create Date: 2026-04-13 09:51:25.180801

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '2886c2bed4d4'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('products', sa.Column('create_at', sa.DateTime(), nullable=True))
    op.alter_column('products', 'price',
               existing_type=sa.NUMERIC(precision=12, scale=0),
               type_=sa.Integer(),
               existing_nullable=False)
    op.drop_column('products', 'created_at')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('products', sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=True))
    op.alter_column('products', 'price',
               existing_type=sa.Integer(),
               type_=sa.NUMERIC(precision=12, scale=0),
               existing_nullable=False)
    op.drop_column('products', 'create_at')
    # ### end Alembic commands ###
